#!/bin/sh

case "$1" in
	start)
	echo "Starting Wi-Fi ..."
	modprobe brcmfmac
        while [ ! -d /sys/class/net/wlan0 ]; do sleep 1; done
	ip link set wlan0 up
	wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
	;;

	stop)
	echo "Stopping Wi-Fi ..."
	killall wpa_supplicant
	ip link set wlan0 down
	;;

	*)
	echo "Usage: $0 {start|stop}"
	;;
esac
