#!/bin/sh

case "$1" in
	start)
	echo "Starting LVGL app ..."
    start-stop-daemon -S -b -x /home/user/lvgl_app
	;;

	stop)
	echo "Stopping LVGL app ..."
    start-stop-daemon -K -x /home/user/lvgl_app
	;;

	*)
	echo "Usage: $0 {start|stop}"
	;;
esac
